In [102]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

Data from < https://www.kaggle.com/neuromusic/avocado-prices >

In [22]:
data = pd.read_csv('avocado.csv', index_col = 0)
data.head()

Date  AveragePrice  Total Volume     4046       4225    4770  \
0  2015-12-27          1.33      64236.62  1036.74   54454.85   48.16   
1  2015-12-20          1.35      54876.98   674.28   44638.81   58.33   
2  2015-12-13          0.93     118220.22   794.70  109149.67  130.50   
3  2015-12-06          1.08      78992.15  1132.00   71976.41   72.58   
4  2015-11-29          1.28      51039.60   941.48   43838.39   75.78   

   Total Bags  Small Bags  Large Bags  XLarge Bags          type  year  region  
0     8696.87     8603.62       93.25          0.0  conventional  2015  Albany  
1     9505.56     9408.07       97.49          0.0  conventional  2015  Albany  
2     8145.35     8042.21      103.14          0.0  conventional  2015  Albany  
3     5811.16     5677.40      133.76          0.0  conventional  2015  Albany  
4     6183.95     5986.26      197.69          0.0  conventional  2015  Albany

In [23]:
data['XLarge Bags'].unique()

array([  0.  ,  33.33, 104.17, ..., 228.27,  12.12,  24.18])

PLU Look up http://indexfresh.com/retail-foodservice/brands/packaging/plus/. 4046: Small; 4225: Large; 4770: Extra Large

In [24]:
data['Date'] = pd.to_datetime(data['Date'])

In [26]:
data['year'].astype('int32')

0     2015
1     2015
2     2015
3     2015
4     2015
      ... 
7     2018
8     2018
9     2018
10    2018
11    2018
Name: year, Length: 18249, dtype: int32

In [27]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 18249 entries, 0 to 11
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype         
---  ------        --------------  -----         
 0   Date          18249 non-null  datetime64[ns]
 1   AveragePrice  18249 non-null  float64       
 2   Total Volume  18249 non-null  float64       
 3   4046          18249 non-null  float64       
 4   4225          18249 non-null  float64       
 5   4770          18249 non-null  float64       
 6   Total Bags    18249 non-null  float64       
 7   Small Bags    18249 non-null  float64       
 8   Large Bags    18249 non-null  float64       
 9   XLarge Bags   18249 non-null  float64       
 10  type          18249 non-null  object        
 11  year          18249 non-null  int64         
 12  region        18249 non-null  object        
dtypes: datetime64[ns](1), float64(9), int64(1), object(2)
memory usage: 1.9+ MB


In [33]:
data = data.rename(columns = {'4046': 'Small', '4225': 'Large', '4770': 'XLarge'})

In [34]:
data.head()

Date  AveragePrice  Total Volume    Small      Large  XLarge  \
0 2015-12-27          1.33      64236.62  1036.74   54454.85   48.16   
1 2015-12-20          1.35      54876.98   674.28   44638.81   58.33   
2 2015-12-13          0.93     118220.22   794.70  109149.67  130.50   
3 2015-12-06          1.08      78992.15  1132.00   71976.41   72.58   
4 2015-11-29          1.28      51039.60   941.48   43838.39   75.78   

   Total Bags  Small Bags  Large Bags  XLarge Bags          type  year  region  
0     8696.87     8603.62       93.25          0.0  conventional  2015  Albany  
1     9505.56     9408.07       97.49          0.0  conventional  2015  Albany  
2     8145.35     8042.21      103.14          0.0  conventional  2015  Albany  
3     5811.16     5677.40      133.76          0.0  conventional  2015  Albany  
4     6183.95     5986.26      197.69          0.0  conventional  2015  Albany

In [66]:
data_partial = data.iloc[0:1000]

In [67]:
data_partial.head()

Date  AveragePrice  Total Volume    Small      Large  XLarge  \
0 2015-12-27          1.33      64236.62  1036.74   54454.85   48.16   
1 2015-12-20          1.35      54876.98   674.28   44638.81   58.33   
2 2015-12-13          0.93     118220.22   794.70  109149.67  130.50   
3 2015-12-06          1.08      78992.15  1132.00   71976.41   72.58   
4 2015-11-29          1.28      51039.60   941.48   43838.39   75.78   

   Total Bags  Small Bags  Large Bags  XLarge Bags          type  year  region  
0     8696.87     8603.62       93.25          0.0  conventional  2015  Albany  
1     9505.56     9408.07       97.49          0.0  conventional  2015  Albany  
2     8145.35     8042.21      103.14          0.0  conventional  2015  Albany  
3     5811.16     5677.40      133.76          0.0  conventional  2015  Albany  
4     6183.95     5986.26      197.69          0.0  conventional  2015  Albany

In [35]:
from ipywidgets import interact

In [42]:
def f(x,y):
    return x+y

In [43]:
w = interact(f,x=[1,2,3,4],y =[1,2,3,4])
# v = interact(f,x=(1,4))

interactive(children=(Dropdown(description='x', options=(1, 2, 3, 4), value=1), Dropdown(description='y', opti…

list = drop downs

tuples = sliders

In [112]:
def plot_line_data(region,kind,y):
    selection = data_partial[
        (data_partial['region'] == region) & (data_partial['type'] == kind)
    ]
    selection.plot('Date',y,kind = 'line')

In [113]:
a = interact(plot_line_data, region = data.region.unique(), kind = ['conventional','organic'],y = ['AveragePrice','Total Volume'])

interactive(children=(Dropdown(description='region', options=('Albany', 'Atlanta', 'BaltimoreWashington', 'Boi…

In [106]:
def summation(x,y):
    return x + y

interact(summation,x = (0,10), y = [0,5,10])

interactive(children=(IntSlider(value=5, description='x', max=10), Dropdown(description='y', options=(0, 5, 10…

<function __main__.summation(x, y)>

In [98]:
a = {'List':'Drop Down','Tuple':'Slider','Boolean':'Check Box','String':'Textbox', }

In [103]:
b = np.array([['List','Drop Down'],['Tuple','Slider'],['Boolean','Check Box'],['String','Textbox']])

In [104]:
pd.DataFrame(b,columns = ['Data Type','Widget'])

Data Type     Widget
0      List  Drop Down
1     Tuple     Slider
2   Boolean  Check Box
3    String    Textbox